import { withBasePath } from '@/lib/base-path';

/**
 * The ART mark.
 *
 * THIS IS THE REAL ASSET, not a trace. `public/art-mark.png` is the supplied icon with
 * everything outside the disc made transparent (so it carries no white square), generated by
 * decoding the original and re-encoding as RGBA.
 *
 * WHY NOT A TRACED SVG, HAVING TRIED THREE TIMES
 *
 * I attempted to reverse-engineer paths from the 108px raster and got it wrong three times. The
 * final measurement showed why the model could never fit: along a single ray through the centre
 * the mark reads gold - white - grey - white - gold, so the white separation is radially
 * non-monotonic and the notch apex is off-centre. A single wedge cannot express that, and a
 * best-fit trace still disagreed with the source on 7% of pixels - precisely the white
 * separation that gives the mark its shape.
 *
 * For a 28px header mark and a favicon, 108px is ample: 28px needs 56px at 2x DPI. Vector would
 * only matter above ~54px. So the exact raster beats an inexact vector here, and my earlier
 * "vector is always better" reasoning was wrong for this size.
 *
 * IF A LARGER RENDERING IS EVER NEEDED - a print asset, a login splash, an email header - get
 * the official vector (SVG/AI/EPS) from whoever holds the brand assets. This component and
 * `app/icon.png` are the only two places to change.
 */
export function ArtMark({ className = '', size = 28 }: { className?: string; size?: number }) {
  return (
    // A plain <img>: it is a local file of a known size, so the Image optimiser buys nothing and
    // width/height are set explicitly to avoid layout shift. A raw src is root-absolute, so
    // unlike next/image it does NOT pick up basePath on its own - hence withBasePath.
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={withBasePath('/art-mark.png')}
      alt=""
      aria-hidden="true"
      width={size}
      height={size}
      className={className}
      style={{ width: size, height: size }}
      draggable={false}
    />
  );
}

/**
 * The lockup: mark plus wordmark. `compact` drops the words for narrow viewports, where the disc
 * alone still identifies the product.
 *
 * The mark is `aria-hidden` and the accessible name lives on the text, so a screen reader hears
 * "ART HRM" once rather than twice.
 */
export function ArtLogo({
  compact = false, size = 28, className = '',
}: { compact?: boolean; size?: number; className?: string }) {
  return (
    <span className={`inline-flex items-center gap-2 ${className}`}>
      <ArtMark size={size} />
      {compact
        ? <span className="sr-only">ART HRM</span>
        : (
          <span className="text-[14.5px] font-semibold tracking-tight text-ink-900">
            ART <span className="font-normal text-ink-500">HRM</span>
          </span>
        )}
    </span>
  );
}
